<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PCBuildProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('product_status')->insertOrIgnore([
            ['id' => 1, 'status_name' => 'Active'],
            ['id' => 2, 'status_name' => 'Inactive'],
        ]);

        $now = Carbon::now();

        $products = [

            // ═════════════════════════════════════════════════════════════════
            // PROCESSORS
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Intel Core i3-12100F',
                'brand'            => 'Intel',
                'type'             => 'PROCESSOR',
                'tags'             => 'None',
                'description'      => '<p>Budget-friendly 4-core / 8-thread Alder Lake processor for entry-level gaming builds. No integrated graphics — pairs perfectly with a dedicated GPU.</p>',
                'discounted_price' => 21900,
                'retail_price'     => 24900,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 35,
                'features'         => [
                    'socket_type'         => 'LGA1700',
                    'compatible_ram_type' => 'DDR4/DDR5',
                    'cores'               => '4',
                    'threads'             => '8',
                    'base_clock_ghz'      => '3.3',
                    'boost_clock_ghz'     => '4.3',
                    'power_consumption'   => '58',
                ],
            ],
            [
                'name'             => 'Intel Core i5-12400F',
                'brand'            => 'Intel',
                'type'             => 'PROCESSOR',
                'tags'             => 'None',
                'description'      => '<p>6-core / 12-thread mid-range gaming CPU on the LGA1700 platform. Exceptional value — no integrated graphics, pairs best with a GPU.</p>',
                'discounted_price' => 38900,
                'retail_price'     => 43000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 28,
                'features'         => [
                    'socket_type'         => 'LGA1700',
                    'compatible_ram_type' => 'DDR4/DDR5',
                    'cores'               => '6',
                    'threads'             => '12',
                    'base_clock_ghz'      => '2.5',
                    'boost_clock_ghz'     => '4.4',
                    'power_consumption'   => '65',
                ],
            ],
            [
                'name'             => 'Intel Core i7-13700K',
                'brand'            => 'Intel',
                'type'             => 'PROCESSOR',
                'tags'             => 'Featured',
                'description'      => '<p>16-core (8P+8E) / 24-thread enthusiast CPU. Excellent multi-core and gaming performance. Unlocked for overclocking on Z790/Z690 boards.</p>',
                'discounted_price' => 119000,
                'retail_price'     => 130000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 18,
                'features'         => [
                    'socket_type'         => 'LGA1700',
                    'compatible_ram_type' => 'DDR4/DDR5',
                    'cores'               => '16',
                    'threads'             => '24',
                    'base_clock_ghz'      => '3.4',
                    'boost_clock_ghz'     => '5.4',
                    'power_consumption'   => '125',
                ],
            ],
            [
                'name'             => 'AMD Ryzen 3 4100',
                'brand'            => 'AMD',
                'type'             => 'PROCESSOR',
                'tags'             => 'None',
                'description'      => '<p>Entry-level 4-core / 8-thread AM4 processor for tight budget builds. Works with existing AM4 motherboards and DDR4 memory.</p>',
                'discounted_price' => 16900,
                'retail_price'     => 19000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 40,
                'features'         => [
                    'socket_type'         => 'AM4',
                    'compatible_ram_type' => 'DDR4',
                    'cores'               => '4',
                    'threads'             => '8',
                    'base_clock_ghz'      => '3.8',
                    'boost_clock_ghz'     => '4.0',
                    'power_consumption'   => '65',
                ],
            ],
            [
                'name'             => 'AMD Ryzen 5 5600X',
                'brand'            => 'AMD',
                'type'             => 'PROCESSOR',
                'tags'             => 'Top Rated',
                'description'      => '<p>6-core / 12-thread Zen 3 AM4 CPU with excellent single-core IPC. Best-in-class 1080p gaming performance on the AM4 platform.</p>',
                'discounted_price' => 44900,
                'retail_price'     => 49900,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 30,
                'features'         => [
                    'socket_type'         => 'AM4',
                    'compatible_ram_type' => 'DDR4',
                    'cores'               => '6',
                    'threads'             => '12',
                    'base_clock_ghz'      => '3.7',
                    'boost_clock_ghz'     => '4.6',
                    'power_consumption'   => '65',
                ],
            ],
            [
                'name'             => 'AMD Ryzen 7 5800X3D',
                'brand'            => 'AMD',
                'type'             => 'PROCESSOR',
                'tags'             => 'Top Rated',
                'description'      => '<p>AMD\'s legendary 3D V-Cache gaming CPU. 8-core / 16-thread with 96MB L3 cache — the best gaming processor for the AM4 platform.</p>',
                'discounted_price' => 84900,
                'retail_price'     => 93000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 14,
                'features'         => [
                    'socket_type'         => 'AM4',
                    'compatible_ram_type' => 'DDR4',
                    'cores'               => '8',
                    'threads'             => '16',
                    'base_clock_ghz'      => '3.4',
                    'boost_clock_ghz'     => '4.5',
                    'power_consumption'   => '105',
                ],
            ],
            [
                'name'             => 'AMD Ryzen 7 7700X',
                'brand'            => 'AMD',
                'type'             => 'PROCESSOR',
                'tags'             => 'Featured',
                'description'      => '<p>8-core / 16-thread Zen 4 processor on AM5 platform. Excellent all-round performance for gaming and content creation with DDR5.</p>',
                'discounted_price' => 79900,
                'retail_price'     => 88000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 16,
                'features'         => [
                    'socket_type'         => 'AM5',
                    'compatible_ram_type' => 'DDR5',
                    'cores'               => '8',
                    'threads'             => '16',
                    'base_clock_ghz'      => '4.5',
                    'boost_clock_ghz'     => '5.4',
                    'power_consumption'   => '105',
                ],
            ],
            [
                'name'             => 'AMD Ryzen 9 7900X',
                'brand'            => 'AMD',
                'type'             => 'PROCESSOR',
                'tags'             => 'None',
                'description'      => '<p>12-core / 24-thread Zen 4 processor on AM5. Exceptional multi-threaded performance for 3D rendering, video editing, and high-end gaming.</p>',
                'discounted_price' => 134900,
                'retail_price'     => 148000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 10,
                'features'         => [
                    'socket_type'         => 'AM5',
                    'compatible_ram_type' => 'DDR5',
                    'cores'               => '12',
                    'threads'             => '24',
                    'base_clock_ghz'      => '4.7',
                    'boost_clock_ghz'     => '5.6',
                    'power_consumption'   => '170',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // MOTHERBOARDS
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'MSI PRO B760M-A DDR4 Micro-ATX',
                'brand'            => 'MSI',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'None',
                'description'      => '<p>Entry-level Intel B760 mATX board with DDR4 support. Supports 12th/13th/14th Gen Intel CPUs. Great budget choice for office and gaming builds.</p>',
                'discounted_price' => 28900,
                'retail_price'     => 32000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 22,
                'features'         => [
                    'socket_type'         => 'LGA1700',
                    'form_factor'         => 'mATX',
                    'supported_ram_type'  => 'DDR4',
                    'ram_slots'           => '4',
                    'max_ram_gb'          => '128',
                    'supported_ram_speed' => '3200, 3600, 4400',
                    'm2_slots'            => '2',
                    'sata_ports'          => '4',
                    'usb_a_ports'         => '4',
                    'usb_c_ports'         => '1',
                    'pcie_x16_slots'      => '1',
                    'wifi'                => 'No',
                ],
            ],
            [
                'name'             => 'ASUS PRIME Z790-P DDR5 ATX',
                'brand'            => 'ASUS',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'Featured',
                'description'      => '<p>Mid-range Intel Z790 ATX board with DDR5, PCIe 5.0 x16, 3x M.2 slots, and USB 3.2 Gen 2x2. Supports overclocking on 12th/13th/14th Gen Intel CPUs.</p>',
                'discounted_price' => 72900,
                'retail_price'     => 80000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 14,
                'features'         => [
                    'socket_type'         => 'LGA1700',
                    'form_factor'         => 'ATX',
                    'supported_ram_type'  => 'DDR5',
                    'ram_slots'           => '4',
                    'max_ram_gb'          => '192',
                    'supported_ram_speed' => '4800, 5200, 5600, 6400',
                    'm2_slots'            => '3',
                    'sata_ports'          => '4',
                    'usb_a_ports'         => '6',
                    'usb_c_ports'         => '2',
                    'pcie_x16_slots'      => '2',
                    'wifi'                => 'No',
                ],
            ],
            [
                'name'             => 'Gigabyte Z790 AORUS Elite AX DDR5',
                'brand'            => 'Gigabyte',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'Top Rated',
                'description'      => '<p>High-end Intel Z790 ATX board with Wi-Fi 6E, DDR5, PCIe 5.0 M.2, 20+1+2 VRM phases. Excellent for i9 overclocking builds.</p>',
                'discounted_price' => 109000,
                'retail_price'     => 120000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 8,
                'features'         => [
                    'socket_type'         => 'LGA1700',
                    'form_factor'         => 'ATX',
                    'supported_ram_type'  => 'DDR5',
                    'ram_slots'           => '4',
                    'max_ram_gb'          => '192',
                    'supported_ram_speed' => '4800, 5600, 6400, 7200',
                    'm2_slots'            => '4',
                    'sata_ports'          => '6',
                    'usb_a_ports'         => '8',
                    'usb_c_ports'         => '2',
                    'pcie_x16_slots'      => '2',
                    'wifi'                => 'Yes',
                ],
            ],
            [
                'name'             => 'MSI A520M-A PRO Micro-ATX (AM4)',
                'brand'            => 'MSI',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'None',
                'description'      => '<p>Budget AM4 mATX board for Ryzen 3000/4000/5000 series. DDR4 support, 1x M.2 NVMe, and solid VRM for everyday builds.</p>',
                'discounted_price' => 19900,
                'retail_price'     => 22500,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 30,
                'features'         => [
                    'socket_type'         => 'AM4',
                    'form_factor'         => 'mATX',
                    'supported_ram_type'  => 'DDR4',
                    'ram_slots'           => '2',
                    'max_ram_gb'          => '64',
                    'supported_ram_speed' => '2933, 3200, 3600',
                    'm2_slots'            => '1',
                    'sata_ports'          => '4',
                    'usb_a_ports'         => '4',
                    'usb_c_ports'         => '0',
                    'pcie_x16_slots'      => '1',
                    'wifi'                => 'No',
                ],
            ],
            [
                'name'             => 'ASUS TUF Gaming B550-PLUS WiFi II ATX',
                'brand'            => 'ASUS',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'Featured',
                'description'      => '<p>Reliable B550 ATX board for AMD Ryzen 5000/3000. Wi-Fi 6, 2x M.2, PCIe 4.0, and robust power delivery for mid-range builds.</p>',
                'discounted_price' => 54900,
                'retail_price'     => 61000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 16,
                'features'         => [
                    'socket_type'         => 'AM4',
                    'form_factor'         => 'ATX',
                    'supported_ram_type'  => 'DDR4',
                    'ram_slots'           => '4',
                    'max_ram_gb'          => '128',
                    'supported_ram_speed' => '3200, 3600, 4400',
                    'm2_slots'            => '2',
                    'sata_ports'          => '6',
                    'usb_a_ports'         => '6',
                    'usb_c_ports'         => '1',
                    'pcie_x16_slots'      => '2',
                    'wifi'                => 'Yes',
                ],
            ],
            [
                'name'             => 'Gigabyte X670 AORUS Elite AX (AM5)',
                'brand'            => 'Gigabyte',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'Top Rated',
                'description'      => '<p>Feature-rich AMD X670 ATX board for Ryzen 7000 series. PCIe 5.0 x16, 4x M.2 (PCIe 5.0/4.0), Wi-Fi 6E, and USB4 40Gbps.</p>',
                'discounted_price' => 119000,
                'retail_price'     => 132000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 7,
                'features'         => [
                    'socket_type'         => 'AM5',
                    'form_factor'         => 'ATX',
                    'supported_ram_type'  => 'DDR5',
                    'ram_slots'           => '4',
                    'max_ram_gb'          => '192',
                    'supported_ram_speed' => '4800, 5600, 6000, 6400',
                    'm2_slots'            => '4',
                    'sata_ports'          => '4',
                    'usb_a_ports'         => '6',
                    'usb_c_ports'         => '2',
                    'pcie_x16_slots'      => '2',
                    'wifi'                => 'Yes',
                ],
            ],
            [
                'name'             => 'ASRock B650M Pro RS WiFi mATX (AM5)',
                'brand'            => 'ASRock',
                'type'             => 'MOTHERBOARD',
                'tags'             => 'None',
                'description'      => '<p>Compact mATX AM5 board at a great price. Supports Ryzen 7000 series DDR5, 2x M.2, Wi-Fi 6E. Perfect for budget AM5 small-form-factor builds.</p>',
                'discounted_price' => 49900,
                'retail_price'     => 55000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 18,
                'features'         => [
                    'socket_type'         => 'AM5',
                    'form_factor'         => 'mATX',
                    'supported_ram_type'  => 'DDR5',
                    'ram_slots'           => '2',
                    'max_ram_gb'          => '96',
                    'supported_ram_speed' => '4800, 5200, 5600',
                    'm2_slots'            => '2',
                    'sata_ports'          => '4',
                    'usb_a_ports'         => '4',
                    'usb_c_ports'         => '1',
                    'pcie_x16_slots'      => '1',
                    'wifi'                => 'Yes',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // RAM
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Crucial 8GB DDR4-3200 Single Stick',
                'brand'            => 'Crucial',
                'type'             => 'RAM',
                'tags'             => 'None',
                'description'      => '<p>Reliable single 8GB DDR4 stick at 3200MHz. Good starter option — can be paired with a second stick later for dual-channel.</p>',
                'discounted_price' => 6900,
                'retail_price'     => 7900,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 70,
                'features'         => [
                    'ram_type'          => 'DDR4',
                    'speed_mhz'         => '3200',
                    'capacity_gb'       => '8',
                    'sticks_count'      => '1',
                    'power_consumption' => '3',
                ],
            ],
            [
                'name'             => 'Corsair Vengeance LPX DDR4-3600 32GB (2x16GB)',
                'brand'            => 'Corsair',
                'type'             => 'RAM',
                'tags'             => 'Featured',
                'description'      => '<p>Dual-channel 32GB DDR4 kit at 3600MHz, the sweet spot for AMD Ryzen performance. Low-profile design clears most CPU coolers.</p>',
                'discounted_price' => 22900,
                'retail_price'     => 26000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 45,
                'features'         => [
                    'ram_type'          => 'DDR4',
                    'speed_mhz'         => '3600',
                    'capacity_gb'       => '16',
                    'sticks_count'      => '2',
                    'power_consumption' => '5',
                ],
            ],
            [
                'name'             => 'Kingston FURY Beast DDR4-3200 32GB (2x16GB)',
                'brand'            => 'Kingston',
                'type'             => 'RAM',
                'tags'             => 'None',
                'description'      => '<p>32GB dual-channel DDR4 kit for gaming and content creation. Aggressive heat spreader design with XMP 2.0 support.</p>',
                'discounted_price' => 18900,
                'retail_price'     => 22000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 35,
                'features'         => [
                    'ram_type'          => 'DDR4',
                    'speed_mhz'         => '3200',
                    'capacity_gb'       => '16',
                    'sticks_count'      => '2',
                    'power_consumption' => '5',
                ],
            ],
            [
                'name'             => 'Teamgroup T-Force Delta RGB DDR5-6000 32GB (2x16GB)',
                'brand'            => 'Teamgroup',
                'type'             => 'RAM',
                'tags'             => 'New Arrivals',
                'description'      => '<p>High-speed DDR5-6000 RGB kit optimised for Intel XMP 3.0 and AMD EXPO profiles. 32GB dual-channel for enthusiast gaming builds.</p>',
                'discounted_price' => 36900,
                'retail_price'     => 42000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 22,
                'features'         => [
                    'ram_type'          => 'DDR5',
                    'speed_mhz'         => '6000',
                    'capacity_gb'       => '16',
                    'sticks_count'      => '2',
                    'power_consumption' => '7',
                ],
            ],
            [
                'name'             => 'Corsair Dominator Platinum DDR5-5600 64GB (2x32GB)',
                'brand'            => 'Corsair',
                'type'             => 'RAM',
                'tags'             => 'Featured',
                'description'      => '<p>64GB flagship DDR5 kit at 5600MHz with premium aluminium DHX heatspreader. For workstations, content creation, and high-memory workloads.</p>',
                'discounted_price' => 62900,
                'retail_price'     => 72000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 10,
                'features'         => [
                    'ram_type'          => 'DDR5',
                    'speed_mhz'         => '5600',
                    'capacity_gb'       => '32',
                    'sticks_count'      => '2',
                    'power_consumption' => '8',
                ],
            ],
            [
                'name'             => 'Crucial Pro DDR5-5600 16GB (2x8GB)',
                'brand'            => 'Crucial',
                'type'             => 'RAM',
                'tags'             => 'None',
                'description'      => '<p>Entry-level DDR5 dual-channel kit. Budget-friendly option for first-time DDR5 builds on Intel or AMD AM5 platforms.</p>',
                'discounted_price' => 16900,
                'retail_price'     => 19500,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 50,
                'features'         => [
                    'ram_type'          => 'DDR5',
                    'speed_mhz'         => '5600',
                    'capacity_gb'       => '8',
                    'sticks_count'      => '2',
                    'power_consumption' => '5',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // GRAPHIC CARDS
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'NVIDIA GTX 1650 4GB GDDR6',
                'brand'            => 'NVIDIA',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'None',
                'description'      => '<p>Entry-level 1080p GPU with 4GB GDDR6. No external power connector needed. Ideal for budget gaming and multimedia PCs.</p>',
                'discounted_price' => 34900,
                'retail_price'     => 39000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 20,
                'features'         => [
                    'vram_gb'           => '4',
                    'power_consumption' => '75',
                    'power_connector'   => 'No external',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '1',
                ],
            ],
            [
                'name'             => 'NVIDIA RTX 3060 12GB GDDR6',
                'brand'            => 'NVIDIA',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'None',
                'description'      => '<p>Popular 1080p and 1440p gaming GPU with 12GB GDDR6 and hardware ray tracing. Great for gaming and light creative work.</p>',
                'discounted_price' => 79900,
                'retail_price'     => 88000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 18,
                'features'         => [
                    'vram_gb'           => '12',
                    'power_consumption' => '170',
                    'power_connector'   => '1x 8-pin',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '3',
                ],
            ],
            [
                'name'             => 'AMD Radeon RX 6600 8GB GDDR6',
                'brand'            => 'AMD',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'None',
                'description'      => '<p>AMD RDNA 2 GPU for excellent 1080p gaming. 8GB GDDR6, low 132W TDP, and great rasterization performance for the price.</p>',
                'discounted_price' => 54900,
                'retail_price'     => 62000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 16,
                'features'         => [
                    'vram_gb'           => '8',
                    'power_consumption' => '132',
                    'power_connector'   => '1x 8-pin',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '3',
                ],
            ],
            [
                'name'             => 'AMD Radeon RX 7600 8GB GDDR6',
                'brand'            => 'AMD',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'New Arrivals',
                'description'      => '<p>Latest RDNA 3 GPU for 1080p gaming at excellent value. Features DisplayPort 2.1, AV1 encode/decode, and 165W TDP.</p>',
                'discounted_price' => 74900,
                'retail_price'     => 83000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 15,
                'features'         => [
                    'vram_gb'           => '8',
                    'power_consumption' => '165',
                    'power_connector'   => '1x 8-pin',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '3',
                ],
            ],
            [
                'name'             => 'NVIDIA RTX 4070 Ti Super 16GB GDDR6X',
                'brand'            => 'NVIDIA',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'Top Rated',
                'description'      => '<p>Powerful 4K-capable GPU with 16GB GDDR6X, DLSS 3.5, and Ada Lovelace architecture. Excellent for 1440p high refresh rate gaming.</p>',
                'discounted_price' => 249000,
                'retail_price'     => 275000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 8,
                'features'         => [
                    'vram_gb'           => '16',
                    'power_consumption' => '285',
                    'power_connector'   => '1x 16-pin',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '3',
                ],
            ],
            [
                'name'             => 'AMD Radeon RX 7800 XT 16GB GDDR6',
                'brand'            => 'AMD',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'Featured',
                'description'      => '<p>High-end 1440p RDNA 3 GPU with 16GB GDDR6. Excellent rasterization and a great alternative to the RTX 4070.</p>',
                'discounted_price' => 154900,
                'retail_price'     => 172000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 10,
                'features'         => [
                    'vram_gb'           => '16',
                    'power_consumption' => '263',
                    'power_connector'   => '2x 8-pin',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '3',
                ],
            ],
            [
                'name'             => 'NVIDIA RTX 4080 Super 16GB GDDR6X',
                'brand'            => 'NVIDIA',
                'type'             => 'GRAPHIC CARDS',
                'tags'             => 'Featured',
                'description'      => '<p>Near-flagship Ada Lovelace GPU with 16GB GDDR6X. Exceptional 4K gaming, AI workloads, and content creation performance.</p>',
                'discounted_price' => 379000,
                'retail_price'     => 415000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 5,
                'features'         => [
                    'vram_gb'           => '16',
                    'power_consumption' => '320',
                    'power_connector'   => '1x 16-pin',
                    'hdmi_ports'        => '1',
                    'displayport_ports' => '3',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // POWER SUPPLY
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Cooler Master MWE 450W 80+ White',
                'brand'            => 'Cooler Master',
                'type'             => 'POWER SUPPLY',
                'tags'             => 'None',
                'description'      => '<p>450W non-modular ATX PSU with 80+ White certification. Reliable choice for budget builds with integrated graphics or low-TDP GPUs.</p>',
                'discounted_price' => 9900,
                'retail_price'     => 12000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 45,
                'features'         => [
                    'wattage_w'         => '450',
                    'efficiency_rating' => '80+ White',
                    'psu_form_factor'   => 'ATX',
                    'modular'           => 'Non-Modular',
                ],
            ],
            [
                'name'             => 'Corsair CV 650W 80+ Bronze',
                'brand'            => 'Corsair',
                'type'             => 'POWER SUPPLY',
                'tags'             => 'None',
                'description'      => '<p>650W non-modular 80+ Bronze PSU with Japanese capacitors and a quiet 120mm fan. Good value for mid-range gaming builds.</p>',
                'discounted_price' => 19900,
                'retail_price'     => 23000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 30,
                'features'         => [
                    'wattage_w'         => '650',
                    'efficiency_rating' => '80+ Bronze',
                    'psu_form_factor'   => 'ATX',
                    'modular'           => 'Non-Modular',
                ],
            ],
            [
                'name'             => 'be quiet! Pure Power 12 M 750W 80+ Gold',
                'brand'            => 'be quiet!',
                'type'             => 'POWER SUPPLY',
                'tags'             => 'Featured',
                'description'      => '<p>750W semi-modular 80+ Gold PSU with a silent 120mm fan. Japanese capacitors and ATX 3.0 / PCIe 5.0 native 16-pin connector support.</p>',
                'discounted_price' => 34900,
                'retail_price'     => 39000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 20,
                'features'         => [
                    'wattage_w'         => '750',
                    'efficiency_rating' => '80+ Gold',
                    'psu_form_factor'   => 'ATX',
                    'modular'           => 'Semi-Modular',
                ],
            ],
            [
                'name'             => 'EVGA SuperNOVA 850W G6 80+ Gold Fully Modular',
                'brand'            => 'EVGA',
                'type'             => 'POWER SUPPLY',
                'tags'             => 'Top Rated',
                'description'      => '<p>850W fully modular 80+ Gold PSU with a compact 140mm design. Eco mode fan, 10-year warranty, and native PCIe 5.0 connector.</p>',
                'discounted_price' => 49900,
                'retail_price'     => 56000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 14,
                'features'         => [
                    'wattage_w'         => '850',
                    'efficiency_rating' => '80+ Gold',
                    'psu_form_factor'   => 'ATX',
                    'modular'           => 'Fully Modular',
                ],
            ],
            [
                'name'             => 'Corsair HX1200 1200W 80+ Platinum',
                'brand'            => 'Corsair',
                'type'             => 'POWER SUPPLY',
                'tags'             => 'None',
                'description'      => '<p>1200W fully modular 80+ Platinum PSU for extreme builds with dual GPUs or high-end RTX 4090 workstations. Zero RPM mode below 40% load.</p>',
                'discounted_price' => 84900,
                'retail_price'     => 94000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 8,
                'features'         => [
                    'wattage_w'         => '1200',
                    'efficiency_rating' => '80+ Platinum',
                    'psu_form_factor'   => 'ATX',
                    'modular'           => 'Fully Modular',
                ],
            ],
            [
                'name'             => 'Seasonic Prime TX-1000 80+ Titanium',
                'brand'            => 'Seasonic',
                'type'             => 'POWER SUPPLY',
                'tags'             => 'Featured',
                'description'      => '<p>Premium 1000W fully modular 80+ Titanium PSU — the most efficient ATX rating. 12-year warranty and fanless operation below 30% load.</p>',
                'discounted_price' => 79900,
                'retail_price'     => 89000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 6,
                'features'         => [
                    'wattage_w'         => '1000',
                    'efficiency_rating' => '80+ Titanium',
                    'psu_form_factor'   => 'ATX',
                    'modular'           => 'Fully Modular',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // SSD NVME
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Crucial P3 1TB PCIe 3.0 NVMe',
                'brand'            => 'Crucial',
                'type'             => 'SSD NVME',
                'tags'             => 'None',
                'description'      => '<p>Budget-friendly 1TB NVMe SSD with 3500 MB/s reads. Great boot drive upgrade for any PCIe 3.0 or 4.0 motherboard.</p>',
                'discounted_price' => 11900,
                'retail_price'     => 13500,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 45,
                'features'         => [
                    'storage_type'      => 'NVMe PCIe 3.0',
                    'capacity'          => '1TB',
                    'interface'         => 'M.2 NVMe',
                    'power_consumption' => '5',
                ],
            ],
            [
                'name'             => 'Seagate FireCuda 530 2TB PCIe 4.0 NVMe',
                'brand'            => 'Seagate',
                'type'             => 'SSD NVME',
                'tags'             => 'Top Rated',
                'description'      => '<p>2TB high-performance NVMe SSD with 7300 MB/s reads and 6900 MB/s writes. Ideal for PS5 expansion, gaming rigs, and workstations.</p>',
                'discounted_price' => 44900,
                'retail_price'     => 50000,
                'warranty'         => '5 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 18,
                'features'         => [
                    'storage_type'      => 'NVMe PCIe 4.0',
                    'capacity'          => '2TB',
                    'interface'         => 'M.2 NVMe',
                    'power_consumption' => '8',
                ],
            ],
            [
                'name'             => 'Corsair MP600 Pro NH 4TB PCIe 4.0 NVMe',
                'brand'            => 'Corsair',
                'type'             => 'SSD NVME',
                'tags'             => 'Featured',
                'description'      => '<p>4TB high-capacity NVMe SSD with 7100 MB/s sequential reads. No heatsink — fits motherboard M.2 slots with built-in cooling.</p>',
                'discounted_price' => 79900,
                'retail_price'     => 90000,
                'warranty'         => '5 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 10,
                'features'         => [
                    'storage_type'      => 'NVMe PCIe 4.0',
                    'capacity'          => '4TB',
                    'interface'         => 'M.2 NVMe',
                    'power_consumption' => '10',
                ],
            ],
            [
                'name'             => 'Adata Legend 960 Max 1TB PCIe 4.0 NVMe',
                'brand'            => 'Adata',
                'type'             => 'SSD NVME',
                'tags'             => 'None',
                'description'      => '<p>Mid-range PCIe 4.0 NVMe SSD with 7400 MB/s reads at an affordable price. Good balance of performance and value for gaming builds.</p>',
                'discounted_price' => 17900,
                'retail_price'     => 20500,
                'warranty'         => '5 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 30,
                'features'         => [
                    'storage_type'      => 'NVMe PCIe 4.0',
                    'capacity'          => '1TB',
                    'interface'         => 'M.2 NVMe',
                    'power_consumption' => '6',
                ],
            ],
            [
                'name'             => 'Samsung 970 EVO Plus 500GB PCIe 3.0 NVMe',
                'brand'            => 'Samsung',
                'type'             => 'SSD NVME',
                'tags'             => 'None',
                'description'      => '<p>Reliable 500GB NVMe SSD with 3500 MB/s reads and Samsung V-NAND technology. Trusted long-life SSD for OS installs.</p>',
                'discounted_price' => 10900,
                'retail_price'     => 12500,
                'warranty'         => '5 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 35,
                'features'         => [
                    'storage_type'      => 'NVMe PCIe 3.0',
                    'capacity'          => '500GB',
                    'interface'         => 'M.2 NVMe',
                    'power_consumption' => '4',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // HARD DISK
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'WD Purple 3TB Surveillance HDD',
                'brand'            => 'Western Digital',
                'type'             => 'HARD DISK',
                'tags'             => 'None',
                'description'      => '<p>3TB 5400 RPM HDD optimised for 24/7 NVR and DVR workloads. AllFrame technology reduces frame loss in CCTV storage systems.</p>',
                'discounted_price' => 16900,
                'retail_price'     => 19000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 25,
                'features'         => [
                    'storage_type'      => 'HDD 5400 RPM',
                    'capacity'          => '3TB',
                    'interface'         => '3.5 SATA',
                    'power_consumption' => '8',
                ],
            ],
            [
                'name'             => 'Seagate IronWolf 6TB NAS HDD',
                'brand'            => 'Seagate',
                'type'             => 'HARD DISK',
                'tags'             => 'None',
                'description'      => '<p>6TB NAS-optimised CMR HDD at 5400 RPM with AgileArray technology. 24/7 rated for up to 8-bay NAS enclosures.</p>',
                'discounted_price' => 28900,
                'retail_price'     => 33000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 15,
                'features'         => [
                    'storage_type'      => 'NAS Drive',
                    'capacity'          => '6TB',
                    'interface'         => '3.5 SATA',
                    'power_consumption' => '10',
                ],
            ],
            [
                'name'             => 'WD Black 2TB Performance HDD 7200 RPM',
                'brand'            => 'Western Digital',
                'type'             => 'HARD DISK',
                'tags'             => 'None',
                'description'      => '<p>High-performance 2TB desktop HDD at 7200 RPM with a 64MB cache. Designed for gaming and creative workloads needing fast hard drive access.</p>',
                'discounted_price' => 17900,
                'retail_price'     => 20000,
                'warranty'         => '5 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 22,
                'features'         => [
                    'storage_type'      => 'HDD 7200 RPM',
                    'capacity'          => '2TB',
                    'interface'         => '3.5 SATA',
                    'power_consumption' => '9',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // CASINGS
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Fractal Design Pop Air ATX Mid Tower',
                'brand'            => 'Fractal Design',
                'type'             => 'CASINGS',
                'tags'             => 'Featured',
                'description'      => '<p>Clean, airflow-focused ATX mid-tower with mesh front panel and two 140mm fans pre-installed. Supports ATX / mATX / Mini-ITX motherboards.</p>',
                'discounted_price' => 19900,
                'retail_price'     => 23000,
                'warranty'         => '2 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 18,
                'features'         => [
                    'form_factor_support' => 'ATX',
                    'drive_bays'          => '2x 3.5", 2x 2.5"',
                ],
            ],
            [
                'name'             => 'Phanteks Eclipse G360A ATX Mid Tower',
                'brand'            => 'Phanteks',
                'type'             => 'CASINGS',
                'tags'             => 'Top Rated',
                'description'      => '<p>Stylish ATX mid-tower with mesh front, tempered glass side, and 3x pre-installed D30 fans for excellent airflow. Includes GPU anti-sag bracket.</p>',
                'discounted_price' => 22900,
                'retail_price'     => 26500,
                'warranty'         => '2 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 14,
                'features'         => [
                    'form_factor_support' => 'ATX',
                    'drive_bays'          => '2x 3.5", 3x 2.5"',
                ],
            ],
            [
                'name'             => 'Deepcool CH560 Digital ATX Mid Tower',
                'brand'            => 'Deepcool',
                'type'             => 'CASINGS',
                'tags'             => 'New Arrivals',
                'description'      => '<p>Striking ATX mid-tower with a built-in front LCD display showing temp/usage stats. Comes with 4x pre-installed 140mm fans and tempered glass.</p>',
                'discounted_price' => 28900,
                'retail_price'     => 34000,
                'warranty'         => '1 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 10,
                'features'         => [
                    'form_factor_support' => 'E-ATX',
                    'drive_bays'          => '2x 3.5", 4x 2.5"',
                ],
            ],
            [
                'name'             => 'Fractal Design Define 7 XL Full Tower',
                'brand'            => 'Fractal Design',
                'type'             => 'CASINGS',
                'tags'             => 'None',
                'description'      => '<p>Premium full-tower case with sound-damping panels, modular interior, and support for E-ATX workstation motherboards. Fits up to 420mm radiators.</p>',
                'discounted_price' => 44900,
                'retail_price'     => 51000,
                'warranty'         => '2 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 6,
                'features'         => [
                    'form_factor_support' => 'E-ATX',
                    'drive_bays'          => '4x 3.5", 6x 2.5"',
                ],
            ],
            [
                'name'             => 'Corsair 4000D Airflow ATX Mid Tower',
                'brand'            => 'Corsair',
                'type'             => 'CASINGS',
                'tags'             => 'Featured',
                'description'      => '<p>Popular Corsair ATX mid-tower with a high-airflow front mesh panel. Two 120mm fans included. Spacious interior for 360mm radiators and long GPUs.</p>',
                'discounted_price' => 24900,
                'retail_price'     => 28000,
                'warranty'         => '2 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 16,
                'features'         => [
                    'form_factor_support' => 'ATX',
                    'drive_bays'          => '2x 3.5", 2x 2.5"',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // COOLING & LIGHTING
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Cooler Master Hyper 212 Black Edition Air Cooler',
                'brand'            => 'Cooler Master',
                'type'             => 'COOLING & LIGHTING',
                'tags'             => 'None',
                'description'      => '<p>Classic budget-friendly 120mm tower air cooler with 4 heatpipes and a direct-contact base. Wide socket compatibility. Handles up to 150W TDP.</p>',
                'discounted_price' => 6900,
                'retail_price'     => 8200,
                'warranty'         => '2 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 35,
                'features'         => [
                    'cooler_type'         => 'Air Tower',
                    'socket_compatibility'=> 'LGA1700, LGA1200, AM5, AM4, AM3+',
                    'max_tdp_support'     => '150',
                    'fan_count'           => '1',
                    'power_consumption'   => '3',
                ],
            ],
            [
                'name'             => 'DeepCool AK620 Dual Tower Air Cooler',
                'brand'            => 'DeepCool',
                'type'             => 'COOLING & LIGHTING',
                'tags'             => 'Top Rated',
                'description'      => '<p>High-performance dual tower cooler with two 120mm fans and 6 heatpipes. Handles 260W TDP at a fraction of AIO pricing. Compatible with LGA1700 and AM5.</p>',
                'discounted_price' => 14900,
                'retail_price'     => 17500,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 22,
                'features'         => [
                    'cooler_type'         => 'Air Tower',
                    'socket_compatibility'=> 'LGA1700, LGA1200, AM5, AM4',
                    'max_tdp_support'     => '260',
                    'fan_count'           => '2',
                    'power_consumption'   => '4',
                ],
            ],
            [
                'name'             => 'Arctic Liquid Freezer III 240mm AIO',
                'brand'            => 'Arctic',
                'type'             => 'COOLING & LIGHTING',
                'tags'             => 'Featured',
                'description'      => '<p>High-performance 240mm AIO with an integrated VRM fan on the pump head. Outstanding thermal performance and whisper-quiet 2000 RPM fans.</p>',
                'discounted_price' => 24900,
                'retail_price'     => 28500,
                'warranty'         => '6 months warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 15,
                'features'         => [
                    'cooler_type'         => 'AIO 240mm',
                    'socket_compatibility'=> 'LGA1700, LGA1200, AM5, AM4',
                    'max_tdp_support'     => '300',
                    'fan_count'           => '2',
                    'power_consumption'   => '12',
                ],
            ],
            [
                'name'             => 'Corsair iCUE H100i Elite Capellix XT 240mm AIO',
                'brand'            => 'Corsair',
                'type'             => 'COOLING & LIGHTING',
                'tags'             => 'Featured',
                'description'      => '<p>240mm AIO with ARGB Capellix LEDs on the pump head and two AF120 RGB fans. Controlled via Corsair iCUE software.</p>',
                'discounted_price' => 32900,
                'retail_price'     => 37000,
                'warranty'         => '6 months warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 12,
                'features'         => [
                    'cooler_type'         => 'AIO 240mm',
                    'socket_compatibility'=> 'LGA1700, LGA1200, AM5, AM4',
                    'max_tdp_support'     => '250',
                    'fan_count'           => '2',
                    'power_consumption'   => '14',
                ],
            ],
            [
                'name'             => 'be quiet! Silent Loop 2 360mm AIO',
                'brand'            => 'be quiet!',
                'type'             => 'COOLING & LIGHTING',
                'tags'             => 'Top Rated',
                'description'      => '<p>360mm silent AIO with three 120mm Pure Wings 3 fans running as low as 7 dB(A). Exceptional for i9/Ryzen 9 builds that demand silence.</p>',
                'discounted_price' => 49900,
                'retail_price'     => 56000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 8,
                'features'         => [
                    'cooler_type'         => 'AIO 360mm',
                    'socket_compatibility'=> 'LGA1700, LGA1200, AM5, AM4, TR5',
                    'max_tdp_support'     => '350',
                    'fan_count'           => '3',
                    'power_consumption'   => '16',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // FANS
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'Noctua NF-A12x25 PWM 120mm Fan',
                'brand'            => 'Noctua',
                'type'             => 'FANS',
                'tags'             => 'Top Rated',
                'description'      => '<p>Noctua\'s reference-class 120mm fan with outstanding static pressure and airflow. SSO2 magnetic bearing, 6-year warranty, and near-silent at 23 dB(A).</p>',
                'discounted_price' => 5900,
                'retail_price'     => 6900,
                'warranty'         => '6 years warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 40,
                'features'         => [
                    'cooler_type'       => 'Case Fan',
                    'fan_count'         => '1',
                    'power_consumption' => '1',
                ],
            ],
            [
                'name'             => 'Lian Li UNI FAN SL140 RGB 2-Pack 140mm',
                'brand'            => 'Lian Li',
                'type'             => 'FANS',
                'tags'             => 'Featured',
                'description'      => '<p>Daisy-chain 140mm RGB case fans with infinity mirror design. 2-pack with controller included. High airflow at low noise levels.</p>',
                'discounted_price' => 12900,
                'retail_price'     => 14900,
                'warranty'         => '1 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 25,
                'features'         => [
                    'cooler_type'       => 'Case Fan',
                    'fan_count'         => '2',
                    'power_consumption' => '4',
                ],
            ],
            [
                'name'             => 'Corsair LL120 RGB 3-Pack 120mm Fans',
                'brand'            => 'Corsair',
                'type'             => 'FANS',
                'tags'             => 'None',
                'description'      => '<p>3-pack of 120mm RGB fans with dual light loops (16 LEDs each). Includes Lighting Node Core for iCUE control. Great for RGB builds.</p>',
                'discounted_price' => 11900,
                'retail_price'     => 13900,
                'warranty'         => '2 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 20,
                'features'         => [
                    'cooler_type'       => 'Case Fan',
                    'fan_count'         => '3',
                    'power_consumption' => '5',
                ],
            ],

            // ═════════════════════════════════════════════════════════════════
            // MONITORS & ACCESSORIES (for the PC build section)
            // ═════════════════════════════════════════════════════════════════
            [
                'name'             => 'AOC 24G2SP 24" FHD 165Hz IPS Gaming Monitor',
                'brand'            => 'AOC',
                'type'             => 'MONITORS & ACCESSORIES',
                'tags'             => 'None',
                'description'      => '<p>24-inch Full HD IPS gaming monitor at 165Hz with 1ms MPRT. FreeSync Premium and G-Sync Compatible. Great budget 1080p gaming monitor.</p>',
                'discounted_price' => 34900,
                'retail_price'     => 39500,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 20,
                'features'         => [
                    'resolution'       => '1920x1080 FHD',
                    'refresh_rate_hz'  => '165',
                    'panel_type'       => 'IPS',
                    'response_time_ms' => '1',
                ],
            ],
            [
                'name'             => 'BenQ MOBIUZ EX2710Q 27" QHD 165Hz IPS',
                'brand'            => 'BenQ',
                'type'             => 'MONITORS & ACCESSORIES',
                'tags'             => 'Featured',
                'description'      => '<p>27-inch QHD (2560x1440) IPS gaming monitor at 165Hz with HDR10, FreeSync Premium Pro, and built-in 2.1 channel speakers.</p>',
                'discounted_price' => 64900,
                'retail_price'     => 72000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 12,
                'features'         => [
                    'resolution'       => '2560x1440 QHD',
                    'refresh_rate_hz'  => '165',
                    'panel_type'       => 'IPS',
                    'response_time_ms' => '1',
                    'hdr'              => 'HDR10',
                ],
            ],
            [
                'name'             => 'ASUS ROG Swift OLED PG27AQDM 27" QHD 240Hz',
                'brand'            => 'ASUS',
                'type'             => 'MONITORS & ACCESSORIES',
                'tags'             => 'Top Rated',
                'description'      => '<p>27-inch QHD OLED gaming monitor with 240Hz, 0.03ms response time, true HDR1000 brightness, and vivid 1.07 billion colours. Near-instant pixel response.</p>',
                'discounted_price' => 189000,
                'retail_price'     => 210000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 4,
                'features'         => [
                    'resolution'       => '2560x1440 QHD',
                    'refresh_rate_hz'  => '240',
                    'panel_type'       => 'OLED',
                    'response_time_ms' => '0.03',
                    'hdr'              => 'OLED HDR1000',
                ],
            ],
            [
                'name'             => 'LG UltraGear 32GQ950-B 32" 4K 144Hz UHD IPS',
                'brand'            => 'LG',
                'type'             => 'MONITORS & ACCESSORIES',
                'tags'             => 'Featured',
                'description'      => '<p>32-inch 4K (3840x2160) IPS gaming monitor at 144Hz with NVIDIA G-Sync, VESA DisplayHDR 1000, and Nano IPS wide colour gamut technology.</p>',
                'discounted_price' => 149000,
                'retail_price'     => 168000,
                'warranty'         => '3 year Warranty',
                'in_stock'         => 'In Stock',
                'qty'              => 5,
                'features'         => [
                    'resolution'       => '3840x2160 4K UHD',
                    'refresh_rate_hz'  => '144',
                    'panel_type'       => 'Nano IPS',
                    'response_time_ms' => '1',
                    'hdr'              => 'DisplayHDR 1000',
                ],
            ],
        ];

        // ── Insert ────────────────────────────────────────────────────────────
        $count = 0;
        foreach ($products as $data) {
            $features = $data['features'] ?? [];
            unset($data['features']);

            $data['image']      = 'ProductImages/placeholder.jpg';
            $data['status_id']  = 1;
            $data['created_at'] = $now;
            $data['updated_at'] = $now;
            $data['deal_start'] = null;
            $data['deal_end']   = null;

            $productId = DB::table('products')->insertGetId($data);

            foreach ($features as $name => $value) {
                DB::table('product_features')->insert([
                    'product_id'    => $productId,
                    'feature_name'  => $name,
                    'feature_value' => $value,
                    'created_at'    => $now,
                    'updated_at'    => $now,
                ]);
            }
            $count++;
        }

        $this->command->info("✓ {$count} PC build products seeded.");
    }
}
